name: Scheduled test run

on:
  schedule:
    - cron: '*/2 * * * *' # Runs every 2 mins
  branches:
    - master

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger test run
        if: github.ref == 'refs/heads/master'
        run: echo "Trigger test run"
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

