name: Master workflowui

on:
  workflow_dispatch:
    inputs:
      commit_hash:
        description: 'Commit hash'
        required: true
      pr_number:
        description: 'Pull request number'
        required: true

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run: echo "$inputs.commit_hash"
