name: Master workflowui

on:
  workflow_dispatch:
    inputs:
      commit_hash:
        description: 'Commit hash'
        required: true
      pr_number:
        description: 'Pull request number'
        required: true

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Commit hash: ${{ github.event.inputs.commit_hash }}"
        echo "Pr number: ${{ github.event.inputs.pr_number }}" 
